### ISSUE TITLE
InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.hibernate.HibernatePlugin

### ISSUE THREAD

**Issue by ersinozdemir** [HotswapProjects/openjdk-jdk11u-dcevm#8]
Application  : Hybris Commerce V:1905
When           : While starting server 
Error Log    : HOTSWAP AGENT: 06:31:37.117 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.hibernate.HibernatePlugin' class 'org/hibernate/validator/internal/metadata/provider/AnnotationMetaDataProvider'.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:218)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:112)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:246)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at de.hybris.bootstrap.loader.YURLClassLoader.findClass(YURLClassLoader.java:69)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at de.hybris.bootstrap.loader.YURLClassLoader.loadRegisterAndResolveClass(YURLClassLoader.java:131)
	at de.hybris.bootstrap.loader.YURLClassLoader.loadClass(YURLClassLoader.java:119)
	at de.hybris.bootstrap.loader.PlatformInPlaceClassLoader.loadClass(PlatformInPlaceClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.<init>(BeanMetaDataManager.java:145)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.lambda$createValidator$0(ValidatorFactoryImpl.java:351)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.createValidator(ValidatorFactoryImpl.java:342)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.getValidator(ValidatorFactoryImpl.java:245)
	at de.hybris.platform.validation.services.impl.DefaultValidationService.createCustomizedValidator(DefaultValidationService.java:147)
	at de.hybris.platform.validation.services.impl.DefaultValidationService.getValidator(DefaultValidationService.java:97)
	at de.hybris.platform.validation.services.impl.DefaultValidationService.validate(DefaultValidationService.java:260)
	at de.hybris.platform.validation.services.impl.DefaultValidationService.validate(DefaultValidationService.java:253)
	at de.hybris.platform.validation.interceptors.ValidationInterceptor.onValidate(ValidationInterceptor.java:53)
	at de.hybris.platform.servicelayer.internal.model.impl.wrapper.ModelWrapper.invokeValidateInterceptors(ModelWrapper.java:296)
	at de.hybris.platform.servicelayer.internal.model.impl.wrapper.ModelWrapper.validate(ModelWrapper.java:244)
	at de.hybris.platform.servicelayer.internal.model.extractor.impl.DefaultModelExtractor.process(DefaultModelExtractor.java:57)
	at de.hybris.platform.servicelayer.internal.model.impl.DefaultModelService.performPersistenceOperations(DefaultModelService.java:715)
	at de.hybris.platform.servicelayer.internal.model.impl.DefaultModelService.saveAllInternal(DefaultModelService.java:710)
	at de.hybris.platform.servicelayer.internal.model.impl.DefaultModelService.saveAll(DefaultModelService.java:690)
	at de.hybris.platform.servicelayer.internal.model.impl.DefaultModelService.save(DefaultModelService.java:637)
	at de.hybris.platform.ruleengine.init.impl.DefaultRuleEngineKieModuleSwapper.activateKieModule(DefaultRuleEngineKieModuleSwapper.java:631)
	at de.hybris.platform.ruleengine.init.impl.DefaultRuleEngineBootstrap.activateNewRuleEngineContainer(DefaultRuleEngineBootstrap.java:114)
	at de.hybris.platform.ruleengine.init.impl.DefaultRuleEngineBootstrap.startup(DefaultRuleEngineBootstrap.java:96)
	at de.hybris.platform.ruleengine.event.OnTenantStartupProcessor.lambda$2(OnTenantStartupProcessor.java:111)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at de.hybris.platform.ruleengine.event.OnTenantStartupProcessor.activateRulesModules(OnTenantStartupProcessor.java:111)
	at de.hybris.platform.ruleengine.event.OnTenantStartupProcessor.processOnTenantStartup(OnTenantStartupProcessor.java:79)
	at de.hybris.platform.ruleengine.event.OnTenantStartupProcessor$DefaultRuleEngineTenantListener.afterTenantStartUp(OnTenantStartupProcessor.java:273)
	at de.hybris.platform.core.BlockingTenantStartupNotifier.lambda$1(BlockingTenantStartupNotifier.java:120)
	at de.hybris.platform.core.ClassLoaderUtils.executeWithWebClassLoaderParentIfNeeded(ClassLoaderUtils.java:42)
	at de.hybris.platform.core.BlockingTenantStartupNotifier.notifyAllListeners(BlockingTenantStartupNotifier.java:107)
	at de.hybris.platform.core.BlockingTenantStartupNotifier.executeStartupNotify(BlockingTenantStartupNotifier.java:74)
	at de.hybris.platform.core.AbstractTenant.executeInitsIfNecessary(AbstractTenant.java:1339)
	at de.hybris.platform.core.Registry.assureTenantStarted(Registry.java:679)
	at de.hybris.platform.core.Registry.activateTenant(Registry.java:720)
	at de.hybris.platform.core.Registry.setCurrentTenant(Registry.java:569)
	at de.hybris.platform.core.Registry.activateMasterTenant(Registry.java:628)
	at de.hybris.platform.core.Registry.startup(Registry.java:447)
	at de.hybris.platform.core.ClassLoaderUtils.executeWithWebClassLoaderParentIfNeeded(ClassLoaderUtils.java:42)
	at de.hybris.platform.spring.HybrisContextLoaderListener.startRegistry(HybrisContextLoaderListener.java:326)
	at de.hybris.platform.spring.HybrisContextLoaderListener.doInitWebApplicationContext(HybrisContextLoaderListener.java:212)
	at de.hybris.platform.spring.HybrisContextLoaderListener.initWebApplicationContext(HybrisContextLoaderListener.java:199)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at de.hybris.platform.spring.HybrisContextLoaderListener.contextInitialized(HybrisContextLoaderListener.java:95)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hotswap.agent.javassist.bytecode.DuplicateMemberException: duplicate method: __resetCache in org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider
	at org.hotswap.agent.javassist.bytecode.ClassFile.testExistingMethod(ClassFile.java:685)
	at org.hotswap.agent.javassist.bytecode.ClassFile.addMethod(ClassFile.java:660)
	at org.hotswap.agent.javassist.CtClassType.addMethod(CtClassType.java:1517)
	at org.hotswap.agent.plugin.hibernate.HibernateTransformers.annotationMetaDataProviderRegisterVariable(HibernateTransformers.java:149)
	... 74 more

**Comment by skybber** [comment]
I'm clossing it since it is HA issuse not JVM
